
# What to name the Docker container, last part of direcotry.
# That way can use the same makefile in many projects (assuming
# I run 'make' from the  directory where I have the Dockerfile).
#
TARGET_NAME = $(shell basename `pwd`)

# Where my Docker base dir is.
DOCKER_DATA = /tank/data/docker

# A directory to copy configs from.
# These are not placed in the
# Docker container -- this is for things like SSL cert, etc.
# This entire tree will be placed in $DOCKER_DATA/TARGET_NAME
SRC = files/config

# DEST is the destination for configs and such.
DEST = $(DOCKER_DATA)/$(TARGET_NAME)


# Directories which should exist
DIRS = $(DEST)/var/named/data

# Internal
# COPY_FILES is the list of files which should result.
# Generated by taking the wildcard list of files in SRC, and replacing
# the source dir with the dest dir.
COPY_FILES := $(patsubst $(SRC)/%,$(DEST)/%,$(wildcard $(SRC)/*))


all: container $(COPY_FILES) working_dirs

container: Dockerfile
	docker build -t $(TARGET_NAME) .

working_dirs:
	@echo "Working dirs: $(DIRS)"
	@mkdir -p $(DIRS)

$(DEST)/%: $(SRC)/%
	@echo "COPY_FILES is $(COPY_FILES)"
	@echo "--- copying " $< " to " $@
	@rsync -a -v $< $(DEST)

clean: 
	docker build --no-cache -t $(TARGET_NAME) .
